version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: salutem_db
    environment:
      POSTGRES_USER: salutem
      POSTGRES_PASSWORD: salutem123
      POSTGRES_DB: salutem
    ports:
      - "5432:5432"
    volumes:
      - salutem_data:/var/lib/postgresql/data

volumes:
  salutem_data: